"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const cliente_1 = __importDefault(require("../modelos/cliente"));
const endereco_1 = __importDefault(require("../modelos/endereco"));
const telefone_1 = __importDefault(require("../modelos/telefone"));
const agenda_1 = __importDefault(require("../modelos/agenda"));
const Carteira_1 = __importDefault(require("../modelos/Carteira"));
const tipoDocumento_1 = require("../enumeracoes/tipoDocumento");
const Carteira_2 = __importDefault(require("../modelos/Carteira"));
let titular = new cliente_1.default();
titular.nome = `Pedro de Alcântara João Carlos Leopoldo Salvador`;
titular.nomeSocial = `Dom Pedro II`;
titular.dataCadastro = new Date(1840, 6, 23);
titular.dataNascimento = new Date(1825, 11, 2);
titular.agenda = new agenda_1.default();
titular.endereco = new endereco_1.default();
titular.carteira = new Carteira_2.default();
titular.dependentes;
let telefone = new telefone_1.default();
telefone.ddd = `12`;
telefone.numero = `996379940`;
let agenda = new agenda_1.default();
agenda.telefones.push(telefone);
titular.agenda = agenda;
let endereco = new endereco_1.default();
endereco.rua = `R. do Catete`;
endereco.bairro = `Copacabana`;
endereco.cidade = `Rio de Janeiro`;
endereco.estado = `Rio de Janeiro`;
endereco.pais = `Brasil`;
endereco.codigoPostal = `22220-000`;
let documentos = new Carteira_1.default();
documentos.numero = `12345678-9`;
documentos.tipo = tipoDocumento_1.TipoDocumento.RG;
documentos.dataExpedicao = new Date(1835, 11, 2);
let carteira = new Carteira_2.default();
carteira.documentos.push(documentos);
titular.carteira = carteira;
let dependente = new cliente_1.default();
dependente.nome = `Isabel Cristina Leopoldina Augusta Micaela`;
dependente.nomeSocial = `Princesa Isabel`;
dependente.dataCadastro = new Date(1921, 10, 14);
dependente.dataNascimento = new Date(1846, 6, 29);
dependente.agenda = titular.agenda.clonar();
dependente.titular = titular;
titular.dependentes.push(dependente);
console.log(titular);
console.log(dependente);
console.log(agenda);
console.log(endereco);
console.log(carteira);
